services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - devnet

  mongoku:
    image: huggingface/mongoku:latest
    depends_on:
      - mongo
    ports:
      - "3100:3100"
    environment:
      - MONGOKU_DEFAULT_HOST=mongodb://locals:27017
    networks:
      - devnet


volumes:
  mongo-data:

networks:
  devnet: