ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
== Einführung und Ziele
=== Aufgabenstellung
Live Ticker ist eine Webapplikation, welche es erlaubt den **aktuellen Stand** eines Sport-Matches
zu tracken.
Bisher können folgende Events eines Matches erfasst werden:

* Goals (Mit Spieler und Assist Spieler)
* Kickoff und Ende des Spiels
* Halbzeit, Start- und ende eines Drittels

Weitere Funktionalitäten können der https://github.com/vonivo/WEBLAB/blob/main/Aufgabenstellung.md[Aufgabenstellung.md] entnommen werden

=== Qualitätsziele

|===
|Qualitätsziel |Motivation|Szenario

|Optimiert für Desktop- sowie Mobile-Devices
|Benutzer werden die Applikation meistens auf einem mobilen Gerät nutzen, wohingegen der Erfasser des Matches eher ein Desktop-Gerät verwenden wird.
a|

* Als Benutzer möchte den Aktuellen Stand eines Games vor allem unterwegs auf meinem Handy abfragen können.
* Als Administrator möchte ich die Verwaltung der Spiele auf meinen grossen Desktop-Monitor erledigen können, damit ich eine besser Übersicht habe.


|Performance
|Die Google Lighthouse-Analyse des Prod-Bundles soll einen Durchschnittsscore von >= 90 aufweisen.
a|

* Als Benutzer möchte ich eine Schnelle Ladezeit der Seite, da ich unterwegs teilweise keinen 5G empfang habe.

|Erweiterbarkeit
|Die Applikation soll so strukturiert sein, dass sie einfach erweiterbar ist.
a|

* Als Betreiber der Applikation möchte ich einfach neue Features hinzufügen können, damit
ich dem Benutzer eine möglichst komplette User-Experience bieten kann.

|Reproduzierbarkeit
|Die Applikation soll auf verschiedenen Systeme mit nur einem Befehl starbar sein.
a|
* Als Dozent, welcher diese Arbeit korrigiert, möchte ich die Applikation mit nur einem Befehl (`docker compose up --build`) starten können, damit ich nicht viel Zeit in das Setup investieren muss.
|===

=== Stakeholders
[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _Entwickler_ | _mailto:ivo.vonrickenbach@stud.hslu.ch[Ivo von Rickenbach]_ | _Einhalten Anforderungen und gelernten Best-Practices._
| _Dozent_ | _mailto:dominik.witschard@hslu.ch[Dominik Witschard]_ | _Einhalten der funktionalen und nicht funktionen Anforderungen. Einhalten der Form des Projekts._
| _Anfällige Benutzer_ |  | _Gute User-Experience, Featurecompletness_
|===
