ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Verteilungssicht
=== Produktionsumgebung
Die Anwendung wird vollständig containerisiert betrieben. (`docker-compose.yml`)
Die Deployment-Umgebung besteht aus drei Docker-Containern:

* *Frontend*: Enthält Angular App welche über Nginx ausgeliefert wird.
* *Backend*: Enthält NestJs Applikation
* *MongoDB*: MongoDB 7 als persistente Datenbank.

Die Container sind über das Docker-Netzwerk `devnet` verbunden.
Nach Aussen wird ausschliesslich der Port `80` des Frontends freigegeben.

Die MongoDB-Daten werden über ein Docker Volume `mongo-data` persistent gespeichert.

[plantuml, deployment-overview, svg]
----
@startuml
node "Docker Host" as host {

node "Docker Network: devnet" as network {

node "Frontend Container" as frontend {
  artifact "Nginx\nAngular Production Build" as frontendApp
}

node "Backend Container" as backend {
  artifact "Node.js Backend" as backendApp
}

database "MongoDB 7" as mongo

}

folder "Docker Volume" as volume {
    file "mongo-data" as mongoData
    }
}

actor "Client / Browser" as client

client -> frontend : HTTP :80
frontend --> backend : HTTP :3000
backend -> mongo : MongoDB :27017
mongo -> mongoData : persistent data

@enduml
----

=== E2E-Testumgebung
Auch die Testumgebung für die E2E-Tests wird containerisiert erstellt. (`docker-compose.e2e.yml`)

Einziger Unterschied ist das der Port `4200` für das Frontend exponiert wird.

